packages:
  - apps/*
  - config/*
  - packages/*
  - scripts

catalog:
  zod: 3.23.8

catalogs:
  analytics:
    "@rudderstack/analytics-js": 3.14.0
    "@vercel/analytics": 1.3.1
    
  auth:
    "@workos-inc/authkit-nextjs": 1.2.0
    "@workos-inc/authkit-react": 0.9.0
    "@workos-inc/node": 7.37.1
    "@workos-inc/widgets": 1.0.1

  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": 18.3.11
    "@types/react-dom": 18.3.1

  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.0
    "@types/react-dom": 19.0.0

  stack:
    "@types/node": 22.8.6
    "next": 15.3.0
    "zod": 3.24.1
  
  instrumentation: 
    "@opentelemetry/api": 1.9.0
    "@opentelemetry/api-logs": 0.200.0
    "@opentelemetry/instrumentation": 0.200.0
    "@opentelemetry/sdk-logs": 0.200.0
    "@opentelemetry/sdk-trace-node": 2.0.0
    "@prisma/instrumentation": 6.3.1
    "@sentry/nextjs": 9.13.0
    "@sentry/node": 9.13.0
    "@sentry/opentelemetry": 9.13.0
    "@sentry/react": 9.13.0
    "@vercel/otel": 1.11.0
    "langfuse-vercel": 3.37.2

  ui:
    "@hookform/resolvers": 3.9.1
    "autoprefixer": 10.4.20
    "class-variance-authority": "0.7.1"
    "clsx": "2.1.1"
    "framer-motion": 12.9.4
    "lucide-react": "0.446.0"
    "postcss": 8.4.47
    "tailwindcss": 3.4.14
