packages:
  - apps/*
  - config/*
  - packages/*
  - scripts

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.1
    "@types/react-dom": 19.0.2

  stack:
    "@types/node": 22.12.0
    "next": 16.0.0
    "zod": 3.24.1
  
  otel: 
    "@opentelemetry/api": 1.9.0
    "@opentelemetry/api-logs": 0.200.0
    "@opentelemetry/instrumentation": 0.200.0
    "@opentelemetry/sdk-logs": 0.200.0
    "@opentelemetry/sdk-trace-node": 2.0.0
    "@sentry/nextjs": 9.13.0
    "@sentry/node": 9.13.0
    "@sentry/opentelemetry": 9.13.0
    "@sentry/react": 9.13.0
    "@vercel/otel": 1.11.0
    "langfuse-vercel": 3.37.2
