packages:
  - apps/*
  - config/*
  - packages/*

catalog:
  zod: 3.23.8

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/node": 22.8.6
    "@types/react": 19.0.0
    "@types/react-dom": 19.0.0
  
  instrumentation: 
    "@sentry/nextjs": 9.13.0
    "@sentry/node": 9.13.0
    "@sentry/opentelemetry": 9.13.0
    "@sentry/react": 9.13.0