packages:
  - "apps/**"
  - "config/**"
  - "packages/**"

catalog:
  zod: 3.23.8

catalogs:
  analytics:
    "@rudderstack/analytics-js": 3.14.0
    "@vercel/analytics": 1.3.1

  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.1
    "@types/react-dom": 19.0.2

  stack:
    "@types/node": 22.12.0
    "next": 16.0.0
    "zod": 3.24.1
  
  otel: 
    "@opentelemetry/api": 1.9.0
    "@opentelemetry/api-logs": 0.200.0
    "@opentelemetry/instrumentation": 0.200.0
    "@opentelemetry/sdk-logs": 0.200.0
    "@opentelemetry/sdk-trace-node": 2.0.0
    "@sentry/nextjs": 9.13.0
    "@sentry/node": 9.13.0
    "@sentry/opentelemetry": 9.13.0
    "@sentry/react": 9.13.0
    "@vercel/otel": 1.11.0
    "langfuse-vercel": 3.37.2

  ui:
    "@hookform/resolvers": 3.9.1
    "autoprefixer": 10.4.20
    "class-variance-authority": "0.7.1"
    "clsx": "2.1.1"
    "framer-motion": 12.23.24
    "lucide-react": "0.446.0"
    "postcss": 8.4.47
    "tailwindcss": 3.4.14
    "tailwindcss-animate": 1.0.7
    "tailwind-merge": 2.6.0
