// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "analytics/feature-flags.mdx": () => import("../content/docs/analytics/feature-flags.mdx?collection=docs"), "analytics/identifying-users.mdx": () => import("../content/docs/analytics/identifying-users.mdx?collection=docs"), "analytics/index.mdx": () => import("../content/docs/analytics/index.mdx?collection=docs"), "analytics/tracking-events.mdx": () => import("../content/docs/analytics/tracking-events.mdx?collection=docs"), "auth/email-otp.mdx": () => import("../content/docs/auth/email-otp.mdx?collection=docs"), "auth/google-oauth.mdx": () => import("../content/docs/auth/google-oauth.mdx?collection=docs"), "auth/hooks-reference.mdx": () => import("../content/docs/auth/hooks-reference.mdx?collection=docs"), "auth/index.mdx": () => import("../content/docs/auth/index.mdx?collection=docs"), "auth/protecting-routes.mdx": () => import("../content/docs/auth/protecting-routes.mdx?collection=docs"), "auth/session-management.mdx": () => import("../content/docs/auth/session-management.mdx?collection=docs"), "getting-started/comparisons.mdx": () => import("../content/docs/getting-started/comparisons.mdx?collection=docs"), "getting-started/installation.mdx": () => import("../content/docs/getting-started/installation.mdx?collection=docs"), "getting-started/quickstart.mdx": () => import("../content/docs/getting-started/quickstart.mdx?collection=docs"), "getting-started/what-is.mdx": () => import("../content/docs/getting-started/what-is.mdx?collection=docs"), "cli/add.mdx": () => import("../content/docs/cli/add.mdx?collection=docs"), "cli/index.mdx": () => import("../content/docs/cli/index.mdx?collection=docs"), "cli/init.mdx": () => import("../content/docs/cli/init.mdx?collection=docs"), "cli/troubleshooting.mdx": () => import("../content/docs/cli/troubleshooting.mdx?collection=docs"), "cli/upgrade.mdx": () => import("../content/docs/cli/upgrade.mdx?collection=docs"), "seo/index.mdx": () => import("../content/docs/seo/index.mdx?collection=docs"), "seo/metadata.mdx": () => import("../content/docs/seo/metadata.mdx?collection=docs"), "seo/robots.mdx": () => import("../content/docs/seo/robots.mdx?collection=docs"), "seo/sitemap.mdx": () => import("../content/docs/seo/sitemap.mdx?collection=docs"), "seo/structured-data.mdx": () => import("../content/docs/seo/structured-data.mdx?collection=docs"), "getting-started/guides/deployment.mdx": () => import("../content/docs/getting-started/guides/deployment.mdx?collection=docs"), "getting-started/guides/environment-variables.mdx": () => import("../content/docs/getting-started/guides/environment-variables.mdx?collection=docs"), "getting-started/guides/project-structure.mdx": () => import("../content/docs/getting-started/guides/project-structure.mdx?collection=docs"), }),
};
export default browserCollections;