// @ts-nocheck
import { default as __fd_glob_61 } from "../content/docs/auth/usage/meta.json?collection=meta"
import { default as __fd_glob_60 } from "../content/docs/analytics/usage/meta.json?collection=meta"
import { default as __fd_glob_59 } from "../content/docs/ui/meta.json?collection=meta"
import { default as __fd_glob_58 } from "../content/docs/seo/meta.json?collection=meta"
import { default as __fd_glob_57 } from "../content/docs/getting-started/meta.json?collection=meta"
import { default as __fd_glob_56 } from "../content/docs/emails/meta.json?collection=meta"
import { default as __fd_glob_55 } from "../content/docs/db/meta.json?collection=meta"
import { default as __fd_glob_54 } from "../content/docs/cli/meta.json?collection=meta"
import { default as __fd_glob_53 } from "../content/docs/auth/meta.json?collection=meta"
import { default as __fd_glob_52 } from "../content/docs/analytics/meta.json?collection=meta"
import { default as __fd_glob_51 } from "../content/docs/meta.json?collection=meta"
import * as __fd_glob_50 from "../content/docs/auth/usage/with-auth.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/auth/usage/use-auth.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/auth/usage/require-auth.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/analytics/usage/use-flag.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/analytics/usage/use-analytics.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/analytics/usage/track.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/analytics/usage/reset.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/analytics/usage/page.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/analytics/usage/identify.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/seo/structured-data.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/seo/sitemap.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/seo/robots.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/seo/metadata.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/seo/index.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/ui/theming.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/ui/index.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/ui/components.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/getting-started/what-is.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/getting-started/quickstart.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/getting-started/project-structure.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/getting-started/environment-variables.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/getting-started/comparisons.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/emails/templates.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/emails/sending.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/emails/index.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/deployment/vercel.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/deployment/render.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/deployment/railway.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/deployment/index.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/deployment/fly.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/deployment/cloudflare.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/db/schema.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/db/queries.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/db/migrations.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/db/index.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/cli/upgrade.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/cli/troubleshooting.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/cli/init.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/cli/index.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/cli/agents.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/cli/add.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/auth/session-management.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/auth/index.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/auth/configuration.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/analytics/tracking-events.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/analytics/index.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/analytics/identifying-users.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/analytics/feature-flags.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/analytics/analytics-provider.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/index.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.doc("docs", "content/docs", {"index.mdx": __fd_glob_0, "analytics/analytics-provider.mdx": __fd_glob_1, "analytics/feature-flags.mdx": __fd_glob_2, "analytics/identifying-users.mdx": __fd_glob_3, "analytics/index.mdx": __fd_glob_4, "analytics/tracking-events.mdx": __fd_glob_5, "auth/configuration.mdx": __fd_glob_6, "auth/index.mdx": __fd_glob_7, "auth/session-management.mdx": __fd_glob_8, "cli/add.mdx": __fd_glob_9, "cli/agents.mdx": __fd_glob_10, "cli/index.mdx": __fd_glob_11, "cli/init.mdx": __fd_glob_12, "cli/troubleshooting.mdx": __fd_glob_13, "cli/upgrade.mdx": __fd_glob_14, "db/index.mdx": __fd_glob_15, "db/migrations.mdx": __fd_glob_16, "db/queries.mdx": __fd_glob_17, "db/schema.mdx": __fd_glob_18, "deployment/cloudflare.mdx": __fd_glob_19, "deployment/fly.mdx": __fd_glob_20, "deployment/index.mdx": __fd_glob_21, "deployment/railway.mdx": __fd_glob_22, "deployment/render.mdx": __fd_glob_23, "deployment/vercel.mdx": __fd_glob_24, "emails/index.mdx": __fd_glob_25, "emails/sending.mdx": __fd_glob_26, "emails/templates.mdx": __fd_glob_27, "getting-started/comparisons.mdx": __fd_glob_28, "getting-started/environment-variables.mdx": __fd_glob_29, "getting-started/installation.mdx": __fd_glob_30, "getting-started/project-structure.mdx": __fd_glob_31, "getting-started/quickstart.mdx": __fd_glob_32, "getting-started/what-is.mdx": __fd_glob_33, "ui/components.mdx": __fd_glob_34, "ui/index.mdx": __fd_glob_35, "ui/theming.mdx": __fd_glob_36, "seo/index.mdx": __fd_glob_37, "seo/metadata.mdx": __fd_glob_38, "seo/robots.mdx": __fd_glob_39, "seo/sitemap.mdx": __fd_glob_40, "seo/structured-data.mdx": __fd_glob_41, "analytics/usage/identify.mdx": __fd_glob_42, "analytics/usage/page.mdx": __fd_glob_43, "analytics/usage/reset.mdx": __fd_glob_44, "analytics/usage/track.mdx": __fd_glob_45, "analytics/usage/use-analytics.mdx": __fd_glob_46, "analytics/usage/use-flag.mdx": __fd_glob_47, "auth/usage/require-auth.mdx": __fd_glob_48, "auth/usage/use-auth.mdx": __fd_glob_49, "auth/usage/with-auth.mdx": __fd_glob_50, });

export const meta = await create.meta("meta", "content/docs", {"meta.json": __fd_glob_51, "analytics/meta.json": __fd_glob_52, "auth/meta.json": __fd_glob_53, "cli/meta.json": __fd_glob_54, "db/meta.json": __fd_glob_55, "emails/meta.json": __fd_glob_56, "getting-started/meta.json": __fd_glob_57, "seo/meta.json": __fd_glob_58, "ui/meta.json": __fd_glob_59, "analytics/usage/meta.json": __fd_glob_60, "auth/usage/meta.json": __fd_glob_61, });