name: Run Agent Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env: 
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb

jobs:
  has-changed:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.has-changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
              - 'packages/ai'

  agent-test:
    runs-on: ubuntu-latest
    
    # Only run if packages/ai has changed, to save on openai credits
    needs: has-changed
    if: ${{ needs.has-changed.outputs.changed == 'true' }}

    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.5
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm prisma migrate deploy
      - run: pnpm test
        env:
          DEBUG: "prisma*"
          DATABASE_URL: ${{ env.DATABASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
