#!/bin/bash

# Default to patch if no argument is provided
VERSION_TYPE=${1:-patch}

# Validate input
if [[ "$VERSION_TYPE" != "patch" && "$VERSION_TYPE" != "minor" && "$VERSION_TYPE" != "major" ]]; then
    echo "Invalid version type. Use 'patch', 'minor', or 'major'."
    exit 1
fi

# Execute the bump command
pnpm recursive --filter "./packages/**" exec -- npm version "$VERSION_TYPE"

# Get the bumped version number
BUMPED_VERSION=$(pnpm recursive --filter "./packages/**" exec -- node -p "require('./package.json').version" | uniq) 
git ci -am"chore: bump version to $BUMPED_VERSION"

echo ""
echo "Bumped version to $BUMPED_VERSION"